command: ['flask', '--app', 'app.py', 'run', '--host', '0.0.0.0', '--port', '8000']

env:
  - name: PGHOST
    value: 'ep-morning-waterfall-d8ayddnp.database.us-east-2.cloud.databricks.com'
  - name: PGDATABASE
    value: 'databricks_postgres'
  - name: PGUSER
    value: 'Nirmal'
  - name: PGPASSWORD
    value: 'npg_uLcnGkpS98OC'
  - name: PGPORT
    value: '5432'
  - name: PGSSLMODE
    value: 'require'
  - name: FLASK_SECRET_KEY
    value: 'change-this-to-a-random-string'
